### ISSUE TITLE
upTo() may fail with IllegalArgumentException: Min [0] cannot be larger than max [-1]

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#10]
The given code
```java
String invalidName = upTo(10).with(oneOf('%_')).english()
```
could fails with the exception:
```
java.lang.IllegalArgumentException: Min [0] cannot be larger than max [-1]

	at io.qala.datagen.RandomValue.<init>(RandomValue.java:23)
	at io.qala.datagen.RandomValue.upTo(RandomValue.java:36)
	at io.qala.datagen.StringModifier$Impls$1.modify(StringModifier.java:79)
	at io.qala.datagen.RandomValue.applyStringModifiers(RandomValue.java:138)
	at io.qala.datagen.RandomValue.english(RandomValue.java:93)
```
I'm expecting that it shouldn't fail because I'm using an API that should handle such cases internally.

**Comment by ctapobep** [comment]
The more I think about this the more I'm inclined to think that it was a mistake to introduce `upTo()`. It's vague because of the problems that you mentioned before (not clear if it starts from 0 or from 1) and now this problem. To fix it I either need to break backward compatibility (start from 1) or make logic different for integers and strings (which leads to inconsistency).

What do you think if I simply mark it as deprecated?

**Comment by php-coder** [comment]
> What do you think if I simply mark it as deprecated?

I wouldn't mind because I'm not using it anymore.

**Comment by ctapobep** [comment]
Deprecated. Thanks for pointing at the problem.
