### ISSUE TITLE
StringModifier: turn into functional interface

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#19]
`StringModifier` can be turned into [functional interface](https://www.baeldung.com/java-8-functional-interfaces).

In order to do that, we should move implementation of `modify(List<String>)` method from `WithDefaultBatchModify` class into `StringModifier` and mark it as a default method.

**Comment by ctapobep** [comment]
Why don't you change the case after randomization? E.g. `english(10).toUpperCase()`?

**Comment by ctapobep** [comment]
The reason it was done with an abstract class is because the core lib is compiled and can be used with Java5+. We could drop support for Java5, but there should be at least some justification.

The idea behind a library like Datagen is that you don't clutter your test with low-level logic. Giving an ability to provide a lambda violates this principle. Moreover it's not an _action_ that you want to pass - it's a result that you want to state, so lambdas barely suit here anyway. Instead of `length(10).with((s) -> s.doSomeModifications()).english(10)` you could write `length(10).with(someModifications()).english(10)` and make it more readable. 

I recognize that this is not a strong argument, but I think arguments for both sides are pretty weak. So all in all I'm inclined to keep it as is for now.

**Comment by php-coder** [comment]
Ok, no problem. It was just an idea.

Do you support this library by the way?

**Comment by ctapobep** [comment]
I have plans to introduce changes (that you asked in other requests), add features. But right now I don't have enough time - maybe in 6 months things will change.
