### ISSUE TITLE
Examples should clearer say about whether values included/excluded in a range

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#9]
It's not clear from examples whether arguments of the methods like `between()`, `upTo()` and `length()` are treating as open or closed ranges.

In other words, `between(1, 10).numeric()` is returning strings of length `(1, 10)` or `[1, 10]`.

Could we clarify this moment? And also in the javadoc comments (if this information is missing).

**Comment by ctapobep** [comment]
I started to add JavaDocs - this info must be there for sure. I don't want to include this into README though as it should stay concise and serve for other purposes (luring people).

I don't want to release new version just because of the JavaDocs (though who knows - maybe will do anyway), so maybe will need to first finish something more functional (e.g. #5). So it may take some time.

PS: as for the quick answer - all the boundaries are inclusive. One exception is Double though, I'll have to look into this generator closer.

**Comment by ctapobep** [comment]
Released some of javadocs in 1.3.0
